// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NDTC_WebAPI.Models;

namespace NDTC_WebAPI.Migrations
{
    [DbContext(typeof(NDTC_Context))]
    partial class NDTC_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "1.1.2");

            modelBuilder.Entity("NDTC_WebAPI.Models.Address", b =>
                {
                    b.Property<int>("AddressId");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("HouseNo");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<int>("UserId");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("NDTC_WebAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dob");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<long>("Phone");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NDTC_WebAPI.Models.Address", b =>
                {
                    b.HasOne("NDTC_WebAPI.Models.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("NDTC_WebAPI.Models.Address", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
